language: go

go:
    - tip

install:
    - go get -t ./...
    - curl -sLOf https://raw.githubusercontent.com/rafecolton/fmtpolice/master/coverage
    - go get -u code.google.com/p/go.tools/cmd/cover || go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/axw/gocov/gocov github.com/mattn/goveralls

script:
    - go test ./...
    - bash coverage
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -repotoken 5q0ICCCcMrTFcxAkkneaBNa2g9OLFatsB

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
