language: go

go:
    - 1.4
    - tip

install:
    - go get -t ./...
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - go test ./...
    - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
