language: go

go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - release
    - tip

install:
    - go get -t ./...
    - go get simonwaldherr.de/go/golibs/...
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/axw/gocov/gocov
    - go get github.com/modocache/gover
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - go test -v ./...
    - go test -v -coverprofile=ansi.coverprofile ./ansi
    - go test -v -coverprofile=arg.coverprofile ./arg
    - go test -v -coverprofile=as.coverprofile ./as
    - go test -v -coverprofile=cache.coverprofile ./cache
    - go test -v -coverprofile=file.coverprofile ./file
    - go test -v -coverprofile=graphics.coverprofile ./graphics
    - go test -v -coverprofile=re.coverprofile ./re
    - go test -v -coverprofile=regex.coverprofile ./regex
    - go test -v -coverprofile=ssl.coverprofile ./ssl
    - go test -v -coverprofile=stack.coverprofile ./stack
    - go test -v -coverprofile=xmath.coverprofile ./xmath
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
