language: go

go:
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
    - $HOME/gopath/bin/goveralls -repotoken 5q0ICCCcMrTFcxAkkneaBNa2g9OLFatsB

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
